export const downloadlist = [
    { label: "M3U Plus - HLS", value: "type=m3u_plus&output=hls" },
    { label: "M3U Plus - MPEGTS", value: "type=m3u_plus&output=mpegts" },
    { label: "Standard M3U - HLS", value: "type=m3u&output=hls" },
    { label: "Standard M3U - MPEGTS", value: "type=m3u&output=mpegts" },
    { label: "Enigma 2 - HLS", value: "type=enigma22_script&output=hls" },
    { label: "Enigma 2 - MPEGTS", value: "type=enigma22_script&output=ts" },
    { label: "DreamBox - HLS", value: "type=dreambox&output=hls" },
    { label: "DreamBox - MPEGTS", value: "type=dreambox&output=mpegts" },
    { label: "Giga Blue - HLS", value: "type=gigablue&output=hls" },
    { label: "Giga Blue - MPEGTS", value: "type=gigablue&output=mpegts" },
    { label: "Simple List - HLS", value: "type=simple&output=hls" },
    { label: "Simple List - MPEGTS", value: "type=simple&output=mpegts" },
    { label: "Octagon - HLS", value: "type=octagon&output=hls" },
    { label: "Octagon - MPEGTS", value: "type=octagon&output=mpegts" },
    { label: "Starlive v3 - HLS", value: "type=starlivev3&output=hls" },
    { label: "Starlive v3 - MPEGTS", value: "type=starlivev3&output=mpegts" },
    { label: "Starlive V5 - HLS", value: "type=starlivev5&output=hls" },
    { label: "Starlive V5 - MPEGTS", value: "type=starlivev5&output=mpegts" },
    { label: "MediaStar - HLS", value: "type=mediastar&output=hls" },
    { label: "MediaStar - MPEGTS", value: "type=mediastar&output=mpegts" },
    { label: "Web TV List - HLS", value: "type=webtvlist&output=hls" },
    { label: "Web TV List - MPEGTS", value: "type=webtvlist&output=mpegts" },
    { label: "Ariva - HLS", value: "type=ariva&output=hls" },
    { label: "Ariva - MPEGTS", value: "type=ariva&output=mpegts" },
    { label: "Spark - HLS", value: "type=spark&output=hls" },
    { label: "Spark - MPEGTS", value: "type=spark&output=mpegts" },
    { label: "Geant - HLS", value: "type=gst&output=hls" },
    { label: "Geant - MPEGTS", value: "type=gst&output=mpegts" },
    { label: "Fortec 999 - HLS", value: "type=fps&output=hls" },
    { label: "Fortec 999 - MPEGTS", value: "type=fps&output=mpegts" },
    { label: "Revolution 60/60 - HLS", value: "type=revosun&output=hls" },
    {
        label: "Revolution 60/60 - MPEGTS",
        value: "type=revosun&output=mpegts",
    },
    { label: "Zorro - HLS", value: "type=zorro&output=hls" },
    { label: "Zorro - MPEGTS", value: "type=zorro&output=mpegts" },
];


